from pathlib import Path

BASE_DIR = Path(__file__)

print(BASE_DIR)

test = "sdrttttttttttttttttttttttttttttttttttttttttttsdrttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttsdrtttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"